
# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_ip

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# mqtt_statestream:
#   base_topic: homeassistant/master/states
#   publish_attributes: true
#   publish_timestamps: true

mqtt_eventstream:
  subscribe_topic: homeassistant/+/events

mqtt:
  discovery_prefix: homeassistant/pandemicabin/states