input_select:
  eadu_backup_docker:
    name: Eadu Backup Docker
    options:
      - Pending
      - Running
      - Successful
      - Error
    icon: mdi:backup-restore
  eadu_backup_db:
    name: Eadu Backup Database
    options:
      - Pending
      - Running
      - Successful
      - Error
    icon: mdi:backup-restore
  eadu_backup_nextcloud:
    name: Eadu Backup Nextcloud
    options:
      - Pending
      - Running
      - Successful
      - Error
    icon: mdi:backup-restore

binary_sensor:
  - platform: command_line
    unique_id: nextcloud_interface
    name: Photoprism Web Interface
    command: response=$(curl -LIk -m 3 https://yonder.mmjo.com/login/ -o /dev/null -w "%{http_code}\n" -s); test "$response" -eq 200 && echo "OFF" || echo "ON"
    scan_interval: 60
    value_template: '{{ value }}'
    device_class: 'problem'