input_text:
  homeassistant_token_taliluna:
    name: Taliluna HA Token
    mode: password
    max: 255

binary_sensor:
  - platform: ping
    name: Endor Server Ping
    host: 100.119.81.44
  - platform: command_line
    unique_id: photoprism_web_interface
    name: Photoprism Web Interface
    command: response=$(curl -LIk -m 3 https://photos.mmjo.com/ -o /dev/null -w "%{http_code}\n" -s); test "$response" -eq 200 && echo "OFF" || echo "ON"
    scan_interval: 60
    value_template: '{{ value }}'
    device_class: 'problem'
  - platform: rest
    unique_id: rest_homeassistant_taliluna
    name: Taliluna API Status
    device_class: connectivity
    resource: https://taliluna.mmjo.com/api/
    headers:
      Authorization: "Bearer {{ states('input_text.homeassistant_token_taliluna') }}"
      Content-Type: application/json
    value_template: >-
      {{ "API running." in value }}

sensor:
  - platform: rest
    unique_id: rest_homeassistant_taliluna
    name: Taliluna API Status
    resource: https://taliluna.mmjo.com/api/
    headers:
      Authorization: "Bearer {{ states('input_text.homeassistant_token_taliluna') }}"
      Content-Type: application/json
    value_template: >-
      {{ value }}