binary_sensor:
  - platform: command_line
    name: OpenMediaVault Interface
    command: response=$(curl -LIk -m 3 http://100.77.188.22/#/login -o /dev/null -w "%{http_code}\n" -s); test "$response" -eq 200 && echo "OFF" || echo "ON"
    scan_interval: 60
    value_template: '{{ value }}'
    device_class: 'problem'
  - platform: command_line
    name: Minio Interface
    command: response=$(curl -LIk -m 3 http://100.77.188.22:9001/login -o /dev/null -w "%{http_code}\n" -s); test "$response" -eq 200 && echo "OFF" || echo "ON"
    scan_interval: 60
    value_template: '{{ value }}'
    device_class: 'problem'