input_text:
  token_pandemicabin:
    name: Pandemicabin Token
    mode: password
    max: 255

binary_sensor:
  - platform: rest
    unique_id: rest_pandemicabin
    name: Pandemicabin API Status
    device_class: connectivity
    resource: https://pandemicabin.mmjo.com/api/
    headers:
      Authoriation: "Bearer {{ states('input_text.token_pandemicabin') }}"
      Content_Type: application/json
    value_template: >-
      {{ value_json.message == "API running." }}