input_text:
  homeassistant_token_pandemicabin:
    name: Pandemicabin Token
    mode: password
    max: 255

binary_sensor:
  - platform: rest
    unique_id: rest_homeassistant_pandemicabin
    name: Pandemicabin API Status
    device_class: connectivity
    resource: https://pandemicabin.mmjo.com/api/
    headers:
      Authorization: "Bearer {{ states('input_text.homeassistant_token_pandemicabin') }}"
      Content-Type: application/json
    value_template: >-
      {{ "API running." in value }}
  - platform: command_line
    unique_id: zwavejs_interface_pandemicabin
    name:  Pandemicabin ZwaveJS Interface
    command: response=$(curl -LIk -m 3 http://100.72.82.89:8091/ -o /dev/null -w "%{http_code}\n" -s); test "$response" -eq 200 && echo "ON" || echo "OFF"
    scan_interval: 60
    value_template: '{{ value }}'
    device_class: connectivity