input_text:
  token_panedemicabin:
    name: Pandemicabin Token
    mode: password

binary_sensor:
  - platform: rest
    unique_id: rest_pandemicabin
    name: Pandemicabin API Status
    device_class: connectivity
    resource: https://pandemicabin.mmjo.com/api/
    headers:
      Authoriation: "Bearer {{ input_text.token_pandemicabin }}"
      content_type: application/json
    value_template: >-
      {{ value_json.message == "API running." }}